// <auto-generated />
using System;
using Chronith.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronith.Infrastructure.Migrations.PostgreSQL
{
    [DbContext(typeof(ChronithDbContext))]
    partial class ChronithDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chronith")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.AvailabilityWindowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingTypeId");

                    b.ToTable("availability_windows", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountInCentavos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("checkout_url");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PHP");

                    b.Property<string>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("BookingTypeId", "Status", "Start", "End");

                    b.HasIndex("TenantId", "BookingTypeId", "Start", "End");

                    b.ToTable("bookings", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingReminderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_booking_reminders_BookingId");

                    b.HasIndex("BookingId", "IntervalMinutes")
                        .IsUnique()
                        .HasDatabaseName("IX_booking_reminders_BookingId_IntervalMinutes");

                    b.ToTable("booking_reminders", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingStatusChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ChangedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("booking_status_changes", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableDays")
                        .HasColumnType("text");

                    b.Property<int?>("BufferAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("BufferBeforeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PHP");

                    b.Property<string>("CustomFieldSchema")
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomerCallbackSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CustomerCallbackUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PriceInCentavos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("ReminderIntervals")
                        .HasColumnType("jsonb");

                    b.Property<bool>("RequiresStaffAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("booking_types", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingTypeStaffAssignmentEntity", b =>
                {
                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("BookingTypeId", "StaffMemberId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("booking_type_staff_assignments", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.StaffAvailabilityWindowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("staff_availability_windows", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.StaffMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.ToTable("staff_members", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TenantApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_tenant_api_keys_key_hash");

                    b.HasIndex("TenantId", "IsRevoked")
                        .HasDatabaseName("IX_tenant_api_keys_tenant_id_is_revoked");

                    b.ToTable("tenant_api_keys", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TenantNotificationConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_tenant_notification_configs_TenantId");

                    b.HasIndex("TenantId", "ChannelType")
                        .IsUnique()
                        .HasDatabaseName("IX_tenant_notification_configs_TenantId_ChannelType");

                    b.ToTable("tenant_notification_configs", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TenantUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("TenantUsers", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TenantUserRefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantUserId");

                    b.HasIndex("TokenHash");

                    b.ToTable("TenantUserRefreshTokens", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TimeBlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "Start", "End");

                    b.ToTable("time_blocks", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.WaitlistEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("DesiredEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DesiredStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("OfferedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "BookingTypeId", "Status");

                    b.ToTable("waitlist_entries", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.WebhookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingTypeId");

                    b.HasIndex("TenantId", "BookingTypeId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.ToTable("webhooks", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.WebhookOutboxEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RetryRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WebhookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_webhook_outbox_entries_BookingId");

                    b.HasIndex("BookingTypeId")
                        .HasDatabaseName("IX_webhook_outbox_entries_BookingTypeId");

                    b.HasIndex("WebhookId")
                        .HasDatabaseName("IX_webhook_outbox_entries_WebhookId");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_webhook_outbox_entries_Status_NextRetryAt");

                    b.ToTable("webhook_outbox_entries", "chronith");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.AvailabilityWindowEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.BookingTypeEntity", "BookingType")
                        .WithMany("AvailabilityWindows")
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingType");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.BookingTypeEntity", "BookingType")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.StaffMemberEntity", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId");

                    b.Navigation("BookingType");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingStatusChangeEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.BookingEntity", "Booking")
                        .WithMany("StatusChanges")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingTypeStaffAssignmentEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.BookingTypeEntity", "BookingType")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.StaffMemberEntity", "StaffMember")
                        .WithMany("BookingTypeAssignments")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingType");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.StaffAvailabilityWindowEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.StaffMemberEntity", "StaffMember")
                        .WithMany("AvailabilityWindows")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.TenantUserRefreshTokenEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.TenantUserEntity", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.WebhookEntity", b =>
                {
                    b.HasOne("Chronith.Infrastructure.Persistence.Entities.BookingTypeEntity", "BookingType")
                        .WithMany("Webhooks")
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingType");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingEntity", b =>
                {
                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.BookingTypeEntity", b =>
                {
                    b.Navigation("AvailabilityWindows");

                    b.Navigation("Bookings");

                    b.Navigation("StaffAssignments");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("Chronith.Infrastructure.Persistence.Entities.StaffMemberEntity", b =>
                {
                    b.Navigation("AvailabilityWindows");

                    b.Navigation("BookingTypeAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
