name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions: {}

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'juliusbartolome'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
